import { NextLayout } from "@/types/common";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import Navbar from "@/components/navbar";

const selectedFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: NextLayout) {
  return (
    <html lang="en">
      <body /* className={selectedFont.className} */>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
