import Head from "next/head";
import "antd/dist/antd.css";
import { Skeleton, Form } from "antd";
import { useEffect, useState } from "react";
import PaginationBar from "../components/movies/paginationBar";
import MovieCard from "../components/movies/movieCard";

export default function MoviesGallery() {
  const [loading, setLoading] = useState(false);
  const [movies, setMovies] = useState([]);
  const [pagination, setPagination] = useState({
    pageNo: 1,
    pageSize: 20,
    sortBy: "tomatoes.rotten",
    sortOrder: "desc",
  });
  const [totalCount, setTotalCount] = useState(0);

  useEffect(() => {
    search();
  }, [pagination]);

  const search = async () => {
    setLoading(true);
    const res = await fetch(
      `/api/getMovies?pageNo=${pagination.pageNo}&pageSize=${pagination.pageSize}&sortBy=${pagination.sortBy}&sortOrder=${pagination.sortOrder}`
    );
    const result = await res.json();
    setMovies(result.data);
    setTotalCount(result.totalCount);
    setLoading(false);
  };

  const [form] = Form.useForm();

  const changePagination = () => {
    form.validateFields().then((data) => {
      setPagination((oldData) => ({ ...oldData, ...data }));
    });
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <PaginationBar
          pagination={pagination}
          setPagination={setPagination}
          changePagination={changePagination}
          form={form}
          totalCount={totalCount}
        />
        <Skeleton loading={loading} active>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              gap: 30,
              justifyContent: "center",
            }}
          >
            {movies.map((movie) => (
              <MovieCard key={movie._id} data={movie} loading={loading} />
            ))}
          </div>
        </Skeleton>
      </main>

      <footer></footer>
    </div>
  );
}
